---
title: "CRMS Vessel compliance decision support tool "
output: 
  flexdashboard::flex_dashboard:
    theme: default
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(caret)
library(randomForest)

all_models <-
  read_rds(
    'models_only.rds'
  ) %>%
  mutate(Accuracy = round(Accuracy * 100, 1),
         low_ci = Accuracy - (1.96 * AccuracySE),
         high_ci = Accuracy + (1.96 * AccuracySE)) 
```

## Column {data-width="500"}

### Data inputs

```{r}
selectizeInput(
  inputId = 'v_type',
  label = h4('Select the vessel type you are assessing'),
  choices =
    c("Cargo",
      "Passenger",
      "RoRo",
      "Reefer",
      "Tanker",
      "Bulk")
)

checkboxGroupInput(
  "niches",
  h4("Select vessel areas for which data is available"),
  choiceNames =
    list(
      "Dry docking support strips",
      "Hull",
      "Other niche area (e.g. bow or stern thruster, bilge keel, stabiliser, discharge pipe, anode)",
      "Propeller and shaft",
      "Rudder and shaft",
      "Sea chest gratings"
    ),
  choiceValues =
    list(
      "ddss",
      "hull",
      "other",
      "propeller_and_shaft",
      "rudder_and_shaft",
      "sea_chest_gratings"
    ),
  selected = list(
    "ddss",
    "hull",
    "other",
    "propeller_and_shaft",
    "rudder_and_shaft",
    "sea_chest_gratings"
  ),
)


helpText(h3("Select the level of fouling (LoF) for each vessel niche area"))
tags$a(href="https://knowledgeauckland.org.nz/media/1820/fouling-rank-scale-updated-guideline-i-davidson-cawthron-auckland-council-2019.pdf", "See details of the LoF scale here")

# 1. Hull
sliderInput(
  "hull",
  "Hull LoF",
  min = 0,
  max = 5,
  value = 0,
  step = .1
)

# 2. propeller_and_shaft
sliderInput(
  "propeller_and_shaft",
  "Propeller and shaft LoF",
  min = 0,
  max = 5,
  value = 0,
  step = .1
)

# 3. rudder_and_shaft
sliderInput(
  "rudder_and_shaft",
  "Rudder and shaft LoF",
  min = 0,
  max = 5,
  value = 0,
  step = .1
)

# 4. ddss
sliderInput(
  "ddss",
  "Dry docking support strips LoF",
  min = 0,
  max = 5,
  value = 0,
  step = .1
)

# 5. sea_chest_gratings
sliderInput(
  "sea_chest_gratings",
  "Sea chest gratings LoF",
  min = 0,
  max = 5,
  value = 0,
  step = .1
)

# 6. other
sliderInput(
  "other",
  "Other niche areas LoF",
  min = 0,
  max = 5,
  value = 0,
  step = .1
)

```

## Column {data-width="500"}

### Model outputs

```{r}
renderGauge({
  accu <- 
    all_models %>% 
    filter(model_names == paste(c("vessel_type", input$niches), collapse = " + "))

gauge(
  accu$Accuracy,
  min = 0,
  max = 100,
  symbol = '%',
  gaugeSectors(
    success = c(80, 100),
    warning = c(40, 79),
    danger = c(0, 39)
  )
)

})

```

### Compliance prediction

```{r}
renderValueBox({
  
if(!is.null(input$niches)){
new_dat <-
  tibble(
    vessel_type = input$v_type,
    ddss = input$ddss,
    hull = input$hull,
    propeller_and_shaft = input$propeller_and_shaft,
    rudder_and_shaft = input$rudder_and_shaft,
    sea_chest_gratings = input$sea_chest_gratings,
    other = input$other
  )  

crms_pred <-
  all_models %>% 
  filter(model_names== paste(c("vessel_type", input$niches), collapse = " + ")) %>% 
  mutate(res = map(mod, ~ predict(.x, newdata = new_dat, type = 'raw'))) %>%
  unnest(cols = res) %>% 
  select(res)

valueBox(value = crms_pred, icon = "fa-ship")
}
  
  else{valueBox(value = "Select at least one vessel area", icon = "fa-ship")}
  
})

```


### Fail probability (%)

```{r}
renderValueBox({
  if (!is.null(input$niches)) {
    new_dat <-
      tibble(
        vessel_type = input$v_type,
        ddss = input$ddss,
        hull = input$hull,
        propeller_and_shaft = input$propeller_and_shaft,
        rudder_and_shaft = input$rudder_and_shaft,
        sea_chest_gratings = input$sea_chest_gratings,
        other = input$other
      )
    
    fail_prob <-
      all_models %>%
      filter(model_names == paste(c("vessel_type", input$niches), collapse = " + ")) %>%
      mutate(res = map(mod, ~ predict(
        .x, newdata = new_dat, type = 'prob'
      ))) %>%
      unnest(cols = res) %>%
      select(fail) %>%
      mutate(fail = fail * 100)
    
    valueBox(value = fail_prob,
             icon = "fa-thumbs-down",
             color = "#e85129")
  }
  
  else{valueBox(value = "Select at least one vessel area", icon = "fa-ship")}
  
})

```

### Pass probability (%)

```{r}
renderValueBox({
if(!is.null(input$niches)){
  new_dat <-
  tibble(
    vessel_type = input$v_type,
    ddss = input$ddss,
    hull = input$hull,
    propeller_and_shaft = input$propeller_and_shaft,
    rudder_and_shaft = input$rudder_and_shaft,
    sea_chest_gratings = input$sea_chest_gratings,
    other = input$other
  )

pass_prob <-
  all_models %>%
  filter(model_names == paste(c("vessel_type", input$niches), collapse = " + ")) %>%
  mutate(res = map(mod, ~ predict(.x, newdata = new_dat, type = 'prob'))) %>%
  unnest(cols = res) %>%
  select(pass) %>%
  mutate(pass = pass * 100)

    valueBox(value = pass_prob,
             icon = "fa-thumbs-up",
             color = "#85bb5b")
    
}
   else{valueBox(value = "Select at least one vessel area", icon = "fa-ship")}
  
})

```

### Wep application information

```{r}
helpText(HTML('<p style="font-size: 11pt"> The aim of this web application is to support the implementation of the Craft Risk Management Standard (CRMS) by predicting compliance by vessel type, based on the level of fouling (LoF) of different hull and niche areas. Predictions are obtained using a machine learning classification algorithm trained using data from 380 international commercial vessels sampled between 2007 and 2021. Developed by the Cawthron Institute, with funding from Ministry for Primary Industries, under project 405762: Optimisation of Vessel Inspections for Biofouling.</p>'))
br()
img(src = "caw.webp",
    height = 75,
    width = 250)
br()
helpText(HTML('<p style="font-size: 9pt"> Disclaimer: Please note that this decision support tool is provided as a guide only. While all due care has been made, Cawthron cannot be held accountable for the accuracy of information nor the way it is interpreted and applied by external parties </p>'))
 
```
